run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gocyclo:
    min-complexity: 15
  
  funlen:
    lines: 60
    statements: 40
  
  gocognit:
    min-complexity: 20
  
  lll:
    line-length: 120
  
  unused:
    check-exported: true
  
  unparam:
    check-exported: true
  
  goimports:
    local-prefixes: github.com/luiz-simples/keyp.git

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - misspell
    - unconvert

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen
        - gocognit
        - gocyclo
        - lll
    
    - path: cmd/
      linters:
        - errcheck
    
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
      source: "defer.*Close"
    
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
      source: "_ ="

  max-issues-per-linter: 0
  max-same-issues: 0